### ISSUE TITLE
Function Set-LABTimeZone limited

### ISSUE THREAD

**Issue by andrewbbrown** [bottkars/labtools#11]
I noticed that on file: `labtools/labtools/labtools.psm1` on line 554 you have the function `Set-LABTimeZone` which is missing quite a few common time zones, including all of those used in the USA.  There is a list of all the Microsoft Time Zone Index Values (most of which you're currently using) here: `https://msdn.microsoft.com/en-us/library/ms912391(v=winembedded.11).aspx`  I don't mind fixing this and performing a pull request against your repo, but I'm not sure if you've got something more complicated going on in the background that could cause this to break. 

I personally would love it if the time zones `Central Standard Time` and `Eastern Standard Time` :)  Let me know if there is some way I can help!  

The tools you've created are great!  I'll continue to use these and help as I can.

**Comment by bottkars** [comment]
lokked at this this week, not sure wy they where not in. hat a Code ripping them from MSDN, maybe did not take all of them.....
are you Need those on Linux, too ?

**Comment by bottkars** [comment]
will integrate those 139 ones: 
'Get-ChildItem "HKLM:\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Time Zones" | ft name'
